name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install pixi
      uses: prefix-dev/setup-pixi@v0.5.1
      with:
        pixi-version: latest
        cache: true

    - name: Install dependencies
      run: pixi install

    - name: Format check
      run: pixi run format-check

    - name: Lint
      run: pixi run lint

    - name: Type check
      run: pixi run type-check

    - name: Run tests
      run: pixi run test

  check-multi-os:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v4

    - name: Install pixi
      uses: prefix-dev/setup-pixi@v0.5.1
      with:
        pixi-version: latest
        cache: true

    - name: Install dependencies
      run: pixi install

    - name: Run full check
      run: pixi run check
